version: '4'

services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    network_mode: bridge
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
      - 8082:8080

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /deployment/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: bridge
    environment: 
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - /deployment/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - /deployment/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - /deployment/grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    ports:
      - "9100:3000"

  container1:
    image: debian:bookworm
    container_name: container1
    network_mode: bridge
    privileged: true
    tty: true
    ports:
      - 8083:80
