---
- name: Build and run Nginx containers
  hosts: localhost
  become: true
  tasks:
    - name: Build Nginx Docker image
      docker_image:
        build:
          path: /deployment/docker/dockerfiles/nginx
        name: debian
        tag: nginx
        source: build

    - name: Deploy nginx_web_server container
      command: docker compose -f /deployment/docker/docker_compose/nginx/nginx-docker-compose.yml up -d nginx_web_server
      register: docker_compose_web_server

    - name: Get info about nginx_web_server container
      docker_container_info:
          name: "nginx_web_server"
      register: nginx_web_server_info

    - set_fact:
        web_server_ip: "{{ nginx_web_server_info['container']['NetworkSettings']['IPAddress'] }}"

    - name: Generate proxy_server_nginx.conf from jinja template
      template:
        src: templates/nginx_proxy_server_conf.j2
        dest: /deployment/nginx/proxy_server_nginx.conf

    - name: Deploy proxy_web_server container
      command: docker compose -f /deployment/docker/docker_compose/nginx/nginx-docker-compose.yml up -d nginx_proxy_server
      register: docker_compose_proxy_server

    - name: Get info about nginx_proxy_server container
      docker_container_info:
          name: "nginx_proxy_server"
      register: nginx_proxy_server_info

    - name: Status of deploying docker compose for nginx_web_server container
      debug:
        var: docker_compose_web_server.stderr_lines

    - name: IP address of nginx_web_server container
      debug:
        var: nginx_web_server_info['container']['NetworkSettings']['IPAddress']	        

    - name: Status of deploying docker compose for nginx_proxy_server container
      debug:
        var: docker_compose_proxy_server.stderr_lines	      

    - name: IP address of nginx_proxy_server container
      debug:
        var: nginx_proxy_server_info['container']['NetworkSettings']['IPAddress']
