---
- name: Install Docker on Debian
  hosts: localhost
  become: yes  # Ensure the playbook is run with root privileges
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Dockers official GPG key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Set up the Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update the apt package index again
      apt:
        update_cache: yes

    - name: Install Docker Engine, CLI, and Containerd
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        
    - name: Change ulimit parameter in /etc/init.d/docker file. (This will solve problem with starting docker service)
      ansible.builtin.replace:
        path: /etc/init.d/docker
        regexp: 'ulimit -Hn 524288'
        replace: 'ulimit -n 524288' 

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes       