---
- name: Install and configure daemontools
  hosts: localhost
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - build-essential
        - csh

    - name: Create directory /package
      file:
        path: /package
        state: directory
        mode: '1755'

    - name: Download daemontools-0.76.tar.gz
      get_url:
        url: "https://cr.yp.to/daemontools/daemontools-0.76.tar.gz"
        dest: "/package/daemontools-0.76.tar.gz"

    - name: Extract daemontools-0.76.tar.gz
      command: "tar -xzf /package/daemontools-0.76.tar.gz -C /package"
      
    - name: Remove daemontools-0.76.tar.gz
      file:
        path: "/package/daemontools-0.76.tar.gz"
        state: absent

    - name: Replace text in error.h file
      replace:
        path: "/package/admin/daemontools-0.76/src/error.h"
        regexp: "extern int errno"
        replace: "#include <errno.h>"

    - name: Install daemontools
      shell: |
        cd /package/admin/daemontools-0.76
        package/install
      tags: install

    - name: Copy svscanboot init.d script
      copy:
        src: "/deployment/daemontools/init.d/svscanboot"
        dest: "/etc/init.d/svscanboot"
        mode: '0755'
      tags: install

    - name: Enable svscanboot service
      command: "update-rc.d svscanboot defaults"
      tags: install
