---
- name: Stop and remove Zookeeper containers
  hosts: localhost
  become: true
  tasks:
    - name: Stop Zookeeper Docker compose
      command: docker compose -f /cdn77_infra/docker/docker_compose/zookeeper/zookeeper-docker-compose.yml down
      register: zk_compose_deploy

    - name: Show status of Zookeeper Docker compose deployment
      debug:
        var: zk_compose_deploy.stderr_lines
